// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8cY9IX06_ZQaUA0s0jj904Yv900tuAc',
    appId: '1:476023993370:android:e628d0f7e0b4c048fa4da3',
    messagingSenderId: '476023993370',
    projectId: 'rishuden-1',
    storageBucket: 'rishuden-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpopxfGPup1T5SjRpQgJpBqz9HhD1vaJU',
    appId: '1:476023993370:ios:6dddbf8990350696fa4da3',
    messagingSenderId: '476023993370',
    projectId: 'rishuden-1',
    storageBucket: 'rishuden-1.firebasestorage.app',
    iosBundleId: 'com.example.rishuden',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8cY9IX06_ZQaUA0s0jj904Yv900tuAc',
    appId: '1:476023993370:android:e628d0f7e0b4c048fa4da3',
    messagingSenderId: '476023993370',
    projectId: 'rishuden-1',
    storageBucket: 'rishuden-1.firebasestorage.app',
  );
}
